os: linux
sudo: false
dist: trusty
language: generic

before_install:
  # Docker latest
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Docker Compose 1.21.1
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make build
  - make up
  - bin/setup.sh
  - sleep 30s; make test

deploy:
  # Push Docker image
  - provider: script
    skip_cleanup: true
    script: make push
    on:
      tags: true

  # Trigger deploying CI pipeline (prod)
  - provider: script
    script: make deploy-dev
    on:
      branch: 2.x

  # Trigger deploying CI pipeline (prod)
  - provider: script
    script: make deploy
    on:
      tags: true

