os: linux
sudo: false
dist: trusty
language: php
php:
- '7.1'

cache:
  directories:
  - "${HOME}/.cache/composer/files"
  - "${HOME}/.composer/cache/files"

stages:
- name: test
- name: push
- name: deploy

jobs:
  include:

  - stage: test
    services:
      - mysql
    before_script:
      - composer install --prefer-dist
    script:
      - bin/setup.sh
      - bin/test.sh

  # push (dev)
  - stage: push
    if: type = push AND branch IN (1.x, 2.x)
    services:
      - docker
    env:
      - DOCKER_TAG=${TRAVIS_BRANCH}
    script:
      - bin/docker_push.sh

  # push (prod)
  - stage: push
    if: tag =~ ^v\d+\.\d+(\.\d+)?$ # ex) v1.0.0 or v2.0.0
    services:
      - docker
    env:
      - DOCKER_TAG=${TRAVIS_TAG}
    script:
      - bin/docker_push.sh

  # deploy 2.x (dev)
  - stage: deploy
    if: type = push AND branch IN (1.x, 2.x)
    env:
      - CI_TRIGGER_ENV=dev
      - CI_TRIGGER_TARGET=cms-v2-restart
      - CI_TRIGGER_TAG=${TRAVIS_BRANCH}
    script:
      - bin/deploy.sh

  # deploy 1.x (prod)
  - stage: deploy
    if: tag =~ ^v1\.\d+(\.\d+)?$ # ex) v1.0.0
    env:
      - CI_TRIGGER_ENV=prod
      - CI_TRIGGER_TARGET=cms-restart
      - CI_TRIGGER_TAG=${TRAVIS_TAG}
    script:
      - bin/deploy.sh

  # deploy 2.x (prod)
  - stage: deploy
    if: tag =~ ^v2\.\d+(\.\d+)?$ # ex) v2.0.0
    env:
      - CI_TRIGGER_ENV=prod
      - CI_TRIGGER_TARGET=cms-v2-restart
      - CI_TRIGGER_TAG=${TRAVIS_TAG}
    script:
      - bin/deploy.sh
