os: linux
sudo: false
dist: trusty
language: generic

before_install:
  # Docker latest
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Docker Compose 1.21.1
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # MySQL may already be running on the image.
  # https://github.com/travis-ci/travis-ci/issues/8089
  - sudo service mysql stop

script:
  - make build
  - make up
  - echo "Wait for DB start and building.."; sleep 60s
  - make db
  - echo "Wait for applying DB schema change.."; sleep 3s
  - make test

after_scipt:
  - make down

deploy:
  # Push Docker image
  - provider: script
    skip_cleanup: true
    script: make push
    on:
      tags: true

  # Trigger deploying CI pipeline (dev)
  - provider: script
    script: make deploy-dev
    on:
      branch: 2.x

  # Trigger deploying CI pipeline (prod)
  - provider: script
    script: make deploy
    on:
      tags: true

