version: '3.6'

services:
  builder:
    image: ${LOCAL_DOCKER_REPO}-builder:${LOCAL_DOCKER_TAG}
    build:
      context: .
      target: builder

  web:
    image: ${LOCAL_DOCKER_REPO}:${LOCAL_DOCKER_TAG}
    build:
      context: .
